# Generated by Django 3.0.6 on 2020-05-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wechat',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='微信'),
        ),
    ]
