# Generated by Django 3.0.6 on 2020-05-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_tgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tgroup',
            field=models.ManyToManyField(related_name='users', to='users.tGroup', verbose_name='用户组'),
        ),
    ]
