# Generated by Django 3.0.6 on 2020-05-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_wechat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wechat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='微信'),
        ),
    ]
