# Generated by Django 3.0.6 on 2020-05-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_tgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tgroup',
            old_name='notes',
            new_name='content',
        ),
    ]
