# Generated by Django 3.0.6 on 2020-05-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200521_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tgroup',
            old_name='content',
            new_name='comment',
        ),
    ]
