# Generated by Django 3.0.6 on 2020-05-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200518_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type_user',
            field=models.CharField(choices=[(0, '管理员'), (1, '普通用户')], default=2, max_length=10, verbose_name='用户类型'),
            preserve_default=False,
        ),
    ]
