# Generated by Django 3.0.6 on 2020-05-21 14:41

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200521_1418'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tgroup',
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
