# Generated by Django 3.0.6 on 2020-05-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_type_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='type_user',
        ),
    ]
