# Generated by Django 3.0.6 on 2020-05-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200521_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tgroup',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.tGroup', verbose_name='用户组'),
        ),
    ]
