# Generated by Django 3.0.6 on 2020-05-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='application',
            name='env',
            field=models.CharField(choices=[(0, '开发环境'), (1, '测试环境'), (2, 'beta环境'), (3, '生产环境')], max_length=1, verbose_name='环境'),
        ),
    ]
