# Generated by Django 3.0.6 on 2020-05-20 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_tgroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerMisson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='权限名称')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content', models.CharField(max_length=1000, verbose_name='备注')),
                ('app', models.ManyToManyField(blank=True, to='application.Application', verbose_name='应用')),
                ('group', models.ManyToManyField(blank=True, to='users.tGroup', verbose_name='用户组')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'ordering': ('name',),
                'unique_together': {('name',)},
            },
        ),
    ]
