# Generated by Django 3.0.6 on 2020-05-20 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisson',
            name='group',
            field=models.ManyToManyField(blank=True, to='users.tGroup', verbose_name='用户组'),
        ),
        migrations.AddField(
            model_name='permisson',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='permisson',
            unique_together={('name',)},
        ),
    ]
