# Generated by Django 3.0.6 on 2020-05-20 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perm', '0002_auto_20200520_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisson',
            name='app',
            field=models.ManyToManyField(blank=True, related_name='granted_by_permissions', to='application.Application', verbose_name='应用'),
        ),
        migrations.AlterField(
            model_name='permisson',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='granted_by_permissions', to='users.tGroup', verbose_name='用户组'),
        ),
        migrations.AlterField(
            model_name='permisson',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='granted_by_permissions', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
