# Generated by Django 3.0.6 on 2020-05-21 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0003_auto_20200520_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permisson',
            old_name='content',
            new_name='comment',
        ),
    ]
