# Generated by Django 3.0.6 on 2020-05-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0004_auto_20200521_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permisson',
            old_name='app',
            new_name='apps',
        ),
        migrations.RenameField(
            model_name='permisson',
            old_name='group',
            new_name='groups',
        ),
    ]
