# Generated by Django 3.0.6 on 2020-05-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0005_auto_20200521_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permisson',
            old_name='groups',
            new_name='tgroups',
        ),
    ]
